[server]
# maxMessageSize = 500

[theme]
base = "dark"
primaryColor = "#7589A3"
backgroundColor = "#2C3C5F"  # Background color of the main app area
secondaryBackgroundColor = "#354B6E"  # Background color for sidebars, input fields, etc.
textColor = "#E3E7ED"  # Color of the text
font = "Poppins, sans-serif"
baseFontSize = 18

[logger]

# Level of logging for Streamlit's internal logger: "error", "warning",
# "info", or "debug".
#
# Default: "info"
level = "info"
messageFormat = "%(asctime)s %(message)s"