DB_HOST= 'localhost'
DB_PORT= '5432'
DB_USER= 'informes_user'
DB_PASSWORD= 'informes_pass'
DB_NAME= 'informes_db'

LOGO_CORTO= 'static/logo/logo_home_jgm_corto.png'
LOGO_LARGO= 'static/logo/logo_home_jgm_largo.png'
